import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "@/components/provider";

const rebondGrotesque = localFont({
  src: [
    {
      path: "./rebond-grotesque/ESRebondGrotesqueTRIAL-Regular-BF66189040b697b.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./rebond-grotesque/ESRebondGrotesqueTRIAL-Medium-BF6618904088566.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./rebond-grotesque/ESRebondGrotesqueTRIAL-Semibold-BF66189040640ea.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./rebond-grotesque/ESRebondGrotesqueTRIAL-Bold-BF66189040400df.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./rebond-grotesque/ESRebondGrotesqueTRIAL-Extrabold-BF661890400e032.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-rebond-grotesque",
});

export const metadata: Metadata = {
  title: "Roastrava - Roast Strava Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(rebondGrotesque.className, "antialiased tracking-tight")}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
